### PR TITLE
Proposal for Limiting file size

### PR DESCRIPTION
**Pull request by wagerpascal**
Hopefully this time it should be able to merge this time. Placeholder message that can be changed was also added.

:see_no_evil:

### CODE REVIEW

**Comment by YongHaoWu** [comment]
@wagerpascal Hi, thank you for your work. But, 43minutes ago, @thekoc made a pull request, which seems like a good solution. See https://github.com/YongHaoWu/NeteaseCloudMusicFlac/pull/8/commits/2f20433cd4643a1ae466b4130a79cd80a59b8f18
```
+        f = urllib.request.urlopen(songlink)
 +        headers = requests.head(songlink).headers
 +        size = int(headers['Content-Length']) / (1024 ** 2)
```

He just check the header's Content-Length instead of downloading the file and check its size.
How do u think about it?

**Comment by wagerpascal** [comment]
@YongHaoWu I think it's a pretty good idea. It'll save the trouble of downloading the whole file first in the case that it gets thrown out anyways. 

Has it been tested?

**Comment by thekoc** [comment]
At least the songs in my playlist returned correct value corresponding to local files.

**Comment by wagerpascal** [comment]
@thekoc I see. 我支持你 :+1: 
I think it would be a good idea if another person tests it out too (not that I don't trust you) for consistency. Unfortunately I live abroad, so I can't test it myself.

**Comment by YongHaoWu** [comment]
@wagerpascal @thekoc Hi, all. Thanks for your contribution!  I had tested @thekoc 's commit last night, and had made a little fix. See https://github.com/YongHaoWu/NeteaseCloudMusicFlac/commit/c7eb6be6efa23343f157eb8e630be6fa8ff3c710

Python2.7 and Python3 had used some playlists to test  for consistency.
They looks good for me now.

**Pull request closed without merging**
